### ISSUE TITLE
auth login prompt organisation should be organization

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ai#28]
misspelled organization

**Comment by IgorFlint** [comment]
Yep, you're right. I've checked both spellings' popularity. The first time I did check google told me that 's'-version is British. 
![image](https://user-images.githubusercontent.com/47176079/60899033-75553280-a272-11e9-8180-4ee6fafff930.png)

fixed in master as well as the same spelling in a2ml project
